[package]
name = "st-workspaces"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
directories = "4.0.1"
eframe = "0.21.3"
egui = "0.21.0"
tracing-subscriber = "0.3.16"
